### ISSUE TITLE
Italics Typo?

### ISSUE THREAD

**Issue by stevento** [UBCMath/MATH307#2]
https://github.com/UBCMath/MATH307/blob/0363526a2b6acb8bbe97c67ed6c5a3b30ca84f81/linear_equations/differential_equations.md#L243

In the above snippet, I'm unsure if `{\it higher accuracy requires more computations}` was intended to be `*higher accuracy requires more computations*` to apply italics.

**Comment by patrickwalls** [comment]
Thanks. I fixed the typo.
